// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.BonusRefererStatistic.Postgres;

#nullable disable

namespace Service.BonusRefererStatistic.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211202161837_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("referrerstats")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.BonusReferrerStatistic.Domain.Models.ReferrerProfile", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<decimal>("BonusEarned")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CommissionEarned")
                        .HasColumnType("numeric");

                    b.Property<int>("ReferralActivated")
                        .HasColumnType("integer");

                    b.Property<int>("ReferralInvited")
                        .HasColumnType("integer");

                    b.HasKey("ClientId");

                    b.ToTable("profiles", "referrerstats");
                });
#pragma warning restore 612, 618
        }
    }
}
